/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: api.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "api.pb-c.h"
void   unnca__request__init
                     (UNNCA__Request         *message)
{
  static const UNNCA__Request init_value = UNNCA__REQUEST__INIT;
  *message = init_value;
}
size_t unnca__request__get_packed_size
                     (const UNNCA__Request *message)
{
  assert(message->base.descriptor == &unnca__request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t unnca__request__pack
                     (const UNNCA__Request *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &unnca__request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t unnca__request__pack_to_buffer
                     (const UNNCA__Request *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &unnca__request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UNNCA__Request *
       unnca__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UNNCA__Request *)
     protobuf_c_message_unpack (&unnca__request__descriptor,
                                allocator, len, data);
}
void   unnca__request__free_unpacked
                     (UNNCA__Request *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &unnca__request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   unnca__box__init
                     (UNNCA__Box         *message)
{
  static const UNNCA__Box init_value = UNNCA__BOX__INIT;
  *message = init_value;
}
size_t unnca__box__get_packed_size
                     (const UNNCA__Box *message)
{
  assert(message->base.descriptor == &unnca__box__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t unnca__box__pack
                     (const UNNCA__Box *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &unnca__box__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t unnca__box__pack_to_buffer
                     (const UNNCA__Box *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &unnca__box__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UNNCA__Box *
       unnca__box__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UNNCA__Box *)
     protobuf_c_message_unpack (&unnca__box__descriptor,
                                allocator, len, data);
}
void   unnca__box__free_unpacked
                     (UNNCA__Box *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &unnca__box__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   unnca__response__init
                     (UNNCA__Response         *message)
{
  static const UNNCA__Response init_value = UNNCA__RESPONSE__INIT;
  *message = init_value;
}
size_t unnca__response__get_packed_size
                     (const UNNCA__Response *message)
{
  assert(message->base.descriptor == &unnca__response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t unnca__response__pack
                     (const UNNCA__Response *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &unnca__response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t unnca__response__pack_to_buffer
                     (const UNNCA__Response *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &unnca__response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UNNCA__Response *
       unnca__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UNNCA__Response *)
     protobuf_c_message_unpack (&unnca__response__descriptor,
                                allocator, len, data);
}
void   unnca__response__free_unpacked
                     (UNNCA__Response *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &unnca__response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   unnca__auth_request__init
                     (UNNCA__AuthRequest         *message)
{
  static const UNNCA__AuthRequest init_value = UNNCA__AUTH_REQUEST__INIT;
  *message = init_value;
}
size_t unnca__auth_request__get_packed_size
                     (const UNNCA__AuthRequest *message)
{
  assert(message->base.descriptor == &unnca__auth_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t unnca__auth_request__pack
                     (const UNNCA__AuthRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &unnca__auth_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t unnca__auth_request__pack_to_buffer
                     (const UNNCA__AuthRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &unnca__auth_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UNNCA__AuthRequest *
       unnca__auth_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UNNCA__AuthRequest *)
     protobuf_c_message_unpack (&unnca__auth_request__descriptor,
                                allocator, len, data);
}
void   unnca__auth_request__free_unpacked
                     (UNNCA__AuthRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &unnca__auth_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   unnca__auth_response__init
                     (UNNCA__AuthResponse         *message)
{
  static const UNNCA__AuthResponse init_value = UNNCA__AUTH_RESPONSE__INIT;
  *message = init_value;
}
size_t unnca__auth_response__get_packed_size
                     (const UNNCA__AuthResponse *message)
{
  assert(message->base.descriptor == &unnca__auth_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t unnca__auth_response__pack
                     (const UNNCA__AuthResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &unnca__auth_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t unnca__auth_response__pack_to_buffer
                     (const UNNCA__AuthResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &unnca__auth_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UNNCA__AuthResponse *
       unnca__auth_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UNNCA__AuthResponse *)
     protobuf_c_message_unpack (&unnca__auth_response__descriptor,
                                allocator, len, data);
}
void   unnca__auth_response__free_unpacked
                     (UNNCA__AuthResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &unnca__auth_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   unnca__ping_request__init
                     (UNNCA__PingRequest         *message)
{
  static const UNNCA__PingRequest init_value = UNNCA__PING_REQUEST__INIT;
  *message = init_value;
}
size_t unnca__ping_request__get_packed_size
                     (const UNNCA__PingRequest *message)
{
  assert(message->base.descriptor == &unnca__ping_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t unnca__ping_request__pack
                     (const UNNCA__PingRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &unnca__ping_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t unnca__ping_request__pack_to_buffer
                     (const UNNCA__PingRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &unnca__ping_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UNNCA__PingRequest *
       unnca__ping_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UNNCA__PingRequest *)
     protobuf_c_message_unpack (&unnca__ping_request__descriptor,
                                allocator, len, data);
}
void   unnca__ping_request__free_unpacked
                     (UNNCA__PingRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &unnca__ping_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   unnca__ping_response__init
                     (UNNCA__PingResponse         *message)
{
  static const UNNCA__PingResponse init_value = UNNCA__PING_RESPONSE__INIT;
  *message = init_value;
}
size_t unnca__ping_response__get_packed_size
                     (const UNNCA__PingResponse *message)
{
  assert(message->base.descriptor == &unnca__ping_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t unnca__ping_response__pack
                     (const UNNCA__PingResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &unnca__ping_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t unnca__ping_response__pack_to_buffer
                     (const UNNCA__PingResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &unnca__ping_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UNNCA__PingResponse *
       unnca__ping_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UNNCA__PingResponse *)
     protobuf_c_message_unpack (&unnca__ping_response__descriptor,
                                allocator, len, data);
}
void   unnca__ping_response__free_unpacked
                     (UNNCA__PingResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &unnca__ping_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   unnca__get_accelerator_info_request__init
                     (UNNCA__GetAcceleratorInfoRequest         *message)
{
  static const UNNCA__GetAcceleratorInfoRequest init_value = UNNCA__GET_ACCELERATOR_INFO_REQUEST__INIT;
  *message = init_value;
}
size_t unnca__get_accelerator_info_request__get_packed_size
                     (const UNNCA__GetAcceleratorInfoRequest *message)
{
  assert(message->base.descriptor == &unnca__get_accelerator_info_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t unnca__get_accelerator_info_request__pack
                     (const UNNCA__GetAcceleratorInfoRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &unnca__get_accelerator_info_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t unnca__get_accelerator_info_request__pack_to_buffer
                     (const UNNCA__GetAcceleratorInfoRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &unnca__get_accelerator_info_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UNNCA__GetAcceleratorInfoRequest *
       unnca__get_accelerator_info_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UNNCA__GetAcceleratorInfoRequest *)
     protobuf_c_message_unpack (&unnca__get_accelerator_info_request__descriptor,
                                allocator, len, data);
}
void   unnca__get_accelerator_info_request__free_unpacked
                     (UNNCA__GetAcceleratorInfoRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &unnca__get_accelerator_info_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   unnca__get_accelerator_info_response__init
                     (UNNCA__GetAcceleratorInfoResponse         *message)
{
  static const UNNCA__GetAcceleratorInfoResponse init_value = UNNCA__GET_ACCELERATOR_INFO_RESPONSE__INIT;
  *message = init_value;
}
size_t unnca__get_accelerator_info_response__get_packed_size
                     (const UNNCA__GetAcceleratorInfoResponse *message)
{
  assert(message->base.descriptor == &unnca__get_accelerator_info_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t unnca__get_accelerator_info_response__pack
                     (const UNNCA__GetAcceleratorInfoResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &unnca__get_accelerator_info_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t unnca__get_accelerator_info_response__pack_to_buffer
                     (const UNNCA__GetAcceleratorInfoResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &unnca__get_accelerator_info_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UNNCA__GetAcceleratorInfoResponse *
       unnca__get_accelerator_info_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UNNCA__GetAcceleratorInfoResponse *)
     protobuf_c_message_unpack (&unnca__get_accelerator_info_response__descriptor,
                                allocator, len, data);
}
void   unnca__get_accelerator_info_response__free_unpacked
                     (UNNCA__GetAcceleratorInfoResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &unnca__get_accelerator_info_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor unnca__request__field_descriptors[3] =
{
  {
    "width",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(UNNCA__Request, width),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "height",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(UNNCA__Request, height),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(UNNCA__Request, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned unnca__request__field_indices_by_name[] = {
  2,   /* field[2] = data */
  1,   /* field[1] = height */
  0,   /* field[0] = width */
};
static const ProtobufCIntRange unnca__request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor unnca__request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "UNNCA.Request",
  "Request",
  "UNNCA__Request",
  "UNNCA",
  sizeof(UNNCA__Request),
  3,
  unnca__request__field_descriptors,
  unnca__request__field_indices_by_name,
  1,  unnca__request__number_ranges,
  (ProtobufCMessageInit) unnca__request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor unnca__box__field_descriptors[6] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(UNNCA__Box, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(UNNCA__Box, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "width",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(UNNCA__Box, width),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "height",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(UNNCA__Box, height),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "confidence",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(UNNCA__Box, confidence),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "label",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(UNNCA__Box, label),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned unnca__box__field_indices_by_name[] = {
  4,   /* field[4] = confidence */
  3,   /* field[3] = height */
  5,   /* field[5] = label */
  2,   /* field[2] = width */
  0,   /* field[0] = x */
  1,   /* field[1] = y */
};
static const ProtobufCIntRange unnca__box__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor unnca__box__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "UNNCA.Box",
  "Box",
  "UNNCA__Box",
  "UNNCA",
  sizeof(UNNCA__Box),
  6,
  unnca__box__field_descriptors,
  unnca__box__field_indices_by_name,
  1,  unnca__box__number_ranges,
  (ProtobufCMessageInit) unnca__box__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor unnca__response__field_descriptors[2] =
{
  {
    "box_count",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(UNNCA__Response, box_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "boxes",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(UNNCA__Response, n_boxes),
    offsetof(UNNCA__Response, boxes),
    &unnca__box__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned unnca__response__field_indices_by_name[] = {
  0,   /* field[0] = box_count */
  1,   /* field[1] = boxes */
};
static const ProtobufCIntRange unnca__response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor unnca__response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "UNNCA.Response",
  "Response",
  "UNNCA__Response",
  "UNNCA",
  sizeof(UNNCA__Response),
  2,
  unnca__response__field_descriptors,
  unnca__response__field_indices_by_name,
  1,  unnca__response__number_ranges,
  (ProtobufCMessageInit) unnca__response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor unnca__auth_request__field_descriptors[1] =
{
  {
    "uuid",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(UNNCA__AuthRequest, uuid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned unnca__auth_request__field_indices_by_name[] = {
  0,   /* field[0] = uuid */
};
static const ProtobufCIntRange unnca__auth_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor unnca__auth_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "UNNCA.AuthRequest",
  "AuthRequest",
  "UNNCA__AuthRequest",
  "UNNCA",
  sizeof(UNNCA__AuthRequest),
  1,
  unnca__auth_request__field_descriptors,
  unnca__auth_request__field_indices_by_name,
  1,  unnca__auth_request__number_ranges,
  (ProtobufCMessageInit) unnca__auth_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor unnca__auth_response__field_descriptors[2] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(UNNCA__AuthResponse, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uuid",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(UNNCA__AuthResponse, uuid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned unnca__auth_response__field_indices_by_name[] = {
  0,   /* field[0] = code */
  1,   /* field[1] = uuid */
};
static const ProtobufCIntRange unnca__auth_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor unnca__auth_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "UNNCA.AuthResponse",
  "AuthResponse",
  "UNNCA__AuthResponse",
  "UNNCA",
  sizeof(UNNCA__AuthResponse),
  2,
  unnca__auth_response__field_descriptors,
  unnca__auth_response__field_indices_by_name,
  1,  unnca__auth_response__number_ranges,
  (ProtobufCMessageInit) unnca__auth_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor unnca__ping_request__field_descriptors[2] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(UNNCA__PingRequest, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uuid",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(UNNCA__PingRequest, uuid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned unnca__ping_request__field_indices_by_name[] = {
  0,   /* field[0] = code */
  1,   /* field[1] = uuid */
};
static const ProtobufCIntRange unnca__ping_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor unnca__ping_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "UNNCA.PingRequest",
  "PingRequest",
  "UNNCA__PingRequest",
  "UNNCA",
  sizeof(UNNCA__PingRequest),
  2,
  unnca__ping_request__field_descriptors,
  unnca__ping_request__field_indices_by_name,
  1,  unnca__ping_request__number_ranges,
  (ProtobufCMessageInit) unnca__ping_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor unnca__ping_response__field_descriptors[1] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(UNNCA__PingResponse, status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned unnca__ping_response__field_indices_by_name[] = {
  0,   /* field[0] = status */
};
static const ProtobufCIntRange unnca__ping_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor unnca__ping_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "UNNCA.PingResponse",
  "PingResponse",
  "UNNCA__PingResponse",
  "UNNCA",
  sizeof(UNNCA__PingResponse),
  1,
  unnca__ping_response__field_descriptors,
  unnca__ping_response__field_indices_by_name,
  1,  unnca__ping_response__number_ranges,
  (ProtobufCMessageInit) unnca__ping_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define unnca__get_accelerator_info_request__field_descriptors NULL
#define unnca__get_accelerator_info_request__field_indices_by_name NULL
#define unnca__get_accelerator_info_request__number_ranges NULL
const ProtobufCMessageDescriptor unnca__get_accelerator_info_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "UNNCA.GetAcceleratorInfoRequest",
  "GetAcceleratorInfoRequest",
  "UNNCA__GetAcceleratorInfoRequest",
  "UNNCA",
  sizeof(UNNCA__GetAcceleratorInfoRequest),
  0,
  unnca__get_accelerator_info_request__field_descriptors,
  unnca__get_accelerator_info_request__field_indices_by_name,
  0,  unnca__get_accelerator_info_request__number_ranges,
  (ProtobufCMessageInit) unnca__get_accelerator_info_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor unnca__get_accelerator_info_response__field_descriptors[5] =
{
  {
    "version",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(UNNCA__GetAcceleratorInfoResponse, version),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vendor",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(UNNCA__GetAcceleratorInfoResponse, vendor),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "model",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(UNNCA__GetAcceleratorInfoResponse, model),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(UNNCA__GetAcceleratorInfoResponse, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uuid",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(UNNCA__GetAcceleratorInfoResponse, uuid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned unnca__get_accelerator_info_response__field_indices_by_name[] = {
  2,   /* field[2] = model */
  3,   /* field[3] = name */
  4,   /* field[4] = uuid */
  1,   /* field[1] = vendor */
  0,   /* field[0] = version */
};
static const ProtobufCIntRange unnca__get_accelerator_info_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor unnca__get_accelerator_info_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "UNNCA.GetAcceleratorInfoResponse",
  "GetAcceleratorInfoResponse",
  "UNNCA__GetAcceleratorInfoResponse",
  "UNNCA",
  sizeof(UNNCA__GetAcceleratorInfoResponse),
  5,
  unnca__get_accelerator_info_response__field_descriptors,
  unnca__get_accelerator_info_response__field_indices_by_name,
  1,  unnca__get_accelerator_info_response__number_ranges,
  (ProtobufCMessageInit) unnca__get_accelerator_info_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor unnca__detection_service__method_descriptors[4] =
{
  { "Auth", &unnca__auth_request__descriptor, &unnca__auth_response__descriptor },
  { "Detect", &unnca__request__descriptor, &unnca__response__descriptor },
  { "Ping", &unnca__ping_request__descriptor, &unnca__ping_response__descriptor },
  { "GetAcceleratorInfo", &unnca__get_accelerator_info_request__descriptor, &unnca__get_accelerator_info_response__descriptor },
};
const unsigned unnca__detection_service__method_indices_by_name[] = {
  0,        /* Auth */
  1,        /* Detect */
  3,        /* GetAcceleratorInfo */
  2         /* Ping */
};
const ProtobufCServiceDescriptor unnca__detection_service__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "UNNCA.DetectionService",
  "DetectionService",
  "UNNCA__DetectionService",
  "UNNCA",
  4,
  unnca__detection_service__method_descriptors,
  unnca__detection_service__method_indices_by_name
};
void unnca__detection_service__auth(ProtobufCService *service,
                                    const UNNCA__AuthRequest *input,
                                    UNNCA__AuthResponse_Closure closure,
                                    void *closure_data)
{
  assert(service->descriptor == &unnca__detection_service__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void unnca__detection_service__detect(ProtobufCService *service,
                                      const UNNCA__Request *input,
                                      UNNCA__Response_Closure closure,
                                      void *closure_data)
{
  assert(service->descriptor == &unnca__detection_service__descriptor);
  service->invoke(service, 1, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void unnca__detection_service__ping(ProtobufCService *service,
                                    const UNNCA__PingRequest *input,
                                    UNNCA__PingResponse_Closure closure,
                                    void *closure_data)
{
  assert(service->descriptor == &unnca__detection_service__descriptor);
  service->invoke(service, 2, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void unnca__detection_service__get_accelerator_info(ProtobufCService *service,
                                                    const UNNCA__GetAcceleratorInfoRequest *input,
                                                    UNNCA__GetAcceleratorInfoResponse_Closure closure,
                                                    void *closure_data)
{
  assert(service->descriptor == &unnca__detection_service__descriptor);
  service->invoke(service, 3, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void unnca__detection_service__init (UNNCA__DetectionService_Service *service,
                                     UNNCA__DetectionService_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &unnca__detection_service__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
